### ISSUE TITLE
hardware

### ISSUE THREAD

**Issue by ghost** [vacoj/pirrigo#32]
hey. I would like to pick this up and take it further.

Can you list the hardware you got working with it.

I plan to use https://periph.io/device/

**Comment by vacovsky** [comment]
Sorry, I just saw this notification 12 days after you posted.  I'll take an inventory and post it here once I get home.

**Comment by vacovsky** [comment]
- raspberry pi 3
- 2x sainsmart 8-relay module
- a small breadboard
- a canakit gpio breakout 
- low-voltage 24v AC power brick
- irrigation zones are controlled by 24v solenoids, which can be purchased at any hardware store
